### ISSUE TITLE
Publish new version to JetBrains marketplace?

### ISSUE THREAD

**Issue by abrown** [dherre3/intellij-wasmtext-parser-plugin#3]
@dherre3, thanks for the plugin! I've been using it and the plugin is great but the other day I noticed some parse errors (maybe around `local.tee`?) and tracked this repository down. I see that the repo has some changes since 1.0.1 was released and I was hoping you could push the current state to the JetBrains marketplace? I'm looking [here](https://plugins.jetbrains.com/plugin/11409-webassembly-text-format-parser/versions) and I only see old versions. Thanks!

**Comment by dherre3** [comment]
Hey Andrew,

Thanks for the e-mail, I will get around to do this coming week! I'll fix
that issue with local.tee, since I think the current one has `tee_local`
instead.

Regards,

David H.

**Comment by abrown** [comment]
Any issues? I haven't really checked the marketplace but thought I would ping this thread...

**Comment by dherre3** [comment]
I have just submitted an update, it should be up after its evaluated. The plugin now supports v1.1 of the spec: https://webassembly.github.io/spec/core/
There have also been fixes to some of the parser errors and some unit tests for the parser were added. I'll consider this closed.

**Comment by abrown** [comment]
Nice, thanks!
